package ui;

public class VentanaPrincipal extends javax.swing.JFrame {

    private data.ZonaDeCarga zonaDeCarga;

    public VentanaPrincipal() {
        initComponents();
        this.zonaDeCarga = new data.ZonaDeCarga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        btnRegistrarPedido = new javax.swing.JButton();
        btnVerPedidos = new javax.swing.JButton();
        btnIniciarReparto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto1 = new javax.swing.JLabel();
        btnRepartidores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrarPedido.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        btnRegistrarPedido.setText("PEDIDOS");
        btnRegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPedidoActionPerformed(evt);
            }
        });

        btnVerPedidos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnVerPedidos.setText("ENTREGAS");
        btnVerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPedidosActionPerformed(evt);
            }
        });

        btnIniciarReparto.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnIniciarReparto.setText("INICIAR REPARTOS");
        btnIniciarReparto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarRepartoActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("SPEED FAST");

        lblTexto2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblTexto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto2.setText("¿Que desea hacer?");

        lblTexto1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblTexto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto1.setText("¡BIENVENIDO!");

        btnRepartidores.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        btnRepartidores.setText("REPARTIDORES");
        btnRepartidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepartidoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(btnIniciarReparto, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(btnVerPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(btnRegistrarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTexto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTexto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRepartidores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTexto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTexto2)
                .addGap(21, 21, 21)
                .addComponent(btnRepartidores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarReparto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPedidoActionPerformed
        VentanaRegistros ventanaReg = new VentanaRegistros(this.zonaDeCarga);
        ventanaReg.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPedidoActionPerformed

    private void btnIniciarRepartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarRepartoActionPerformed

        if (!zonaDeCarga.pedidosRestantes()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No hay pedidos registrados en la zona de carga. Por favor, registre al menos uno.",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        dao.PedidoDAO pedidoDAO = new dao.PedidoDAO();
        for (model.Pedido p : pedidoDAO.listarTodos()) {
            if (p.getEstado() == model.EstadoPedido.PENDIENTE) {
                pedidoDAO.actualizarEstado(p.getId(), "EN_REPARTO");
            }
        }

        dao.RepartidorDAO repartidorDAO = new dao.RepartidorDAO();
        java.util.List<model.Repartidor> listaRepartidores = repartidorDAO.listarTodos();

        if (listaRepartidores.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encontraron repartidores registrados en la base de datos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (model.Repartidor r : listaRepartidores) {
            r.setZonaDeCarga(zonaDeCarga);
        }

        Thread hiloSimulacion = new Thread(new Runnable() {
            @Override
            public void run() {
                java.util.concurrent.ExecutorService executor = java.util.concurrent.Executors.newFixedThreadPool(listaRepartidores.size());

                for (model.Repartidor r : listaRepartidores) {
                    executor.execute(r);
                }

                executor.shutdown();

                try {
                    if (executor.awaitTermination(2, java.util.concurrent.TimeUnit.MINUTES)) {
                        dao.PedidoDAO daoFinal = new dao.PedidoDAO();
                        for (model.Pedido p : daoFinal.listarTodos()) {
                            if (p.getEstado() == model.EstadoPedido.EN_REPARTO) {
                                daoFinal.actualizarEstado(p.getId(), "ENTREGADO");
                            }
                        }

                        javax.swing.JOptionPane.showMessageDialog(null,
                                "¡Todas las entregas han sido completadas con éxito!",
                                "Simulación Finalizada",
                                javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
            }
        });

        hiloSimulacion.start();

        javax.swing.JOptionPane.showMessageDialog(this,
                "La simulación de repartos ha comenzado. Puede revisar la consola para ver el progreso en tiempo real.",
                "Simulación Iniciada",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnIniciarRepartoActionPerformed

    private void btnVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPedidosActionPerformed
        VentanaLista ventanaLista = new VentanaLista(this.zonaDeCarga);
        ventanaLista.setVisible(true);
    }//GEN-LAST:event_btnVerPedidosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea salir de la aplicación?",
                "Confirmar Salida",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRepartidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepartidoresActionPerformed
        VentanaRepartidores ventanaRepartidores = new VentanaRepartidores();
        ventanaRepartidores.setVisible(true);
    }//GEN-LAST:event_btnRepartidoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarReparto;
    private javax.swing.JButton btnRegistrarPedido;
    private javax.swing.JButton btnRepartidores;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerPedidos;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
